from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from functools import lru_cache
from struct import pack

from PIL import ImageCms

D50_XYZ = (0.9642, 1.0, 0.8249)
D65_XY = (0.3127, 0.3290)
BRADFORD = (
    (0.8951, 0.2664, -0.1614),
    (-0.7502, 1.7135, 0.0367),
    (0.0389, -0.0685, 1.0296),
)
BRADFORD_INVERSE = (
    (0.9869929, -0.1470543, 0.1599627),
    (0.4323053, 0.5183603, 0.0492912),
    (-0.0085287, 0.0400428, 0.9684867),
)
CURVE_SAMPLES = 4096


@dataclass(frozen=True, slots=True)
class RGBColorSpace:
    description: str
    red: tuple[float, float]
    green: tuple[float, float]
    blue: tuple[float, float]
    white: tuple[float, float]
    transfer: str
    gamma: float | None = None


RGB_COLOR_SPACES = {
    "p3": RGBColorSpace(
        description="PixelUp Display P3",
        red=(0.68, 0.32),
        green=(0.265, 0.69),
        blue=(0.15, 0.06),
        white=D65_XY,
        transfer="srgb",
    ),
    "adobergb": RGBColorSpace(
        description="PixelUp Adobe RGB (1998)",
        red=(0.64, 0.33),
        green=(0.21, 0.71),
        blue=(0.15, 0.06),
        white=D65_XY,
        transfer="gamma",
        gamma=2.19921875,
    ),
}


@lru_cache(maxsize=3)
def profile_bytes(name: str) -> bytes:
    if name == "srgb":
        return ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()
    try:
        space = RGB_COLOR_SPACES[name]
    except KeyError as exc:
        raise ValueError(f"unknown ICC profile '{name}'") from exc
    return _rgb_profile(space)


def _rgb_profile(space: RGBColorSpace) -> bytes:
    matrix = _adapt_matrix(
        _rgb_to_xyz_matrix(space),
        source_white=_xy_to_xyz(space.white),
        target_white=D50_XYZ,
    )
    curve = _transfer_curve(space)
    tags = [
        ("desc", _description_tag(space.description)),
        ("cprt", _text_tag("Generated by PixelUp from public color-space constants.")),
        ("wtpt", _xyz_tag(D50_XYZ)),
        ("rXYZ", _xyz_tag((matrix[0][0], matrix[1][0], matrix[2][0]))),
        ("gXYZ", _xyz_tag((matrix[0][1], matrix[1][1], matrix[2][1]))),
        ("bXYZ", _xyz_tag((matrix[0][2], matrix[1][2], matrix[2][2]))),
        ("rTRC", curve),
        ("gTRC", curve),
        ("bTRC", curve),
    ]
    return _profile_with_tags(tags)


def _rgb_to_xyz_matrix(space: RGBColorSpace) -> tuple[tuple[float, float, float], ...]:
    red = _xy_to_xyz(space.red)
    green = _xy_to_xyz(space.green)
    blue = _xy_to_xyz(space.blue)
    primaries = (
        (red[0], green[0], blue[0]),
        (red[1], green[1], blue[1]),
        (red[2], green[2], blue[2]),
    )
    scales = _solve_3x3(primaries, _xy_to_xyz(space.white))
    return tuple(
        tuple(primaries[row][column] * scales[column] for column in range(3))
        for row in range(3)
    )


def _adapt_matrix(
    matrix: tuple[tuple[float, float, float], ...],
    *,
    source_white: tuple[float, float, float],
    target_white: tuple[float, float, float],
) -> tuple[tuple[float, float, float], ...]:
    source_lms = _matrix_vector_multiply(BRADFORD, source_white)
    target_lms = _matrix_vector_multiply(BRADFORD, target_white)
    diagonal = (
        (target_lms[0] / source_lms[0], 0.0, 0.0),
        (0.0, target_lms[1] / source_lms[1], 0.0),
        (0.0, 0.0, target_lms[2] / source_lms[2]),
    )
    adaptation = _matrix_multiply(_matrix_multiply(BRADFORD_INVERSE, diagonal), BRADFORD)
    return _matrix_multiply(adaptation, matrix)


def _profile_with_tags(tags: list[tuple[str, bytes]]) -> bytes:
    tag_count = len(tags)
    tag_table_size = 4 + tag_count * 12
    data = bytearray()
    entries: list[tuple[str, int, int]] = []
    for signature, payload in tags:
        while len(data) % 4:
            data.append(0)
        offset = 128 + tag_table_size + len(data)
        entries.append((signature, offset, len(payload)))
        data.extend(payload)
    while len(data) % 4:
        data.append(0)

    profile_size = 128 + tag_table_size + len(data)
    table = bytearray(pack(">I", tag_count))
    for signature, offset, size in entries:
        table.extend(signature.encode("ascii"))
        table.extend(pack(">II", offset, size))
    return bytes(_header(profile_size) + table + data)


def _header(profile_size: int) -> bytearray:
    header = bytearray(128)
    header[0:4] = pack(">I", profile_size)
    header[4:8] = b"pxup"
    header[8:12] = b"\x02\x10\x00\x00"
    header[12:16] = b"mntr"
    header[16:20] = b"RGB "
    header[20:24] = b"XYZ "
    header[24:36] = pack(">6H", 2026, 1, 1, 0, 0, 0)
    header[36:40] = b"acsp"
    header[64:68] = pack(">I", 0)
    header[68:80] = _xyz_number(D50_XYZ)
    header[80:84] = b"pxup"
    return header


def _description_tag(text: str) -> bytes:
    encoded = text.encode("ascii") + b"\0"
    return (
        b"desc"
        + b"\0" * 4
        + pack(">I", len(encoded))
        + encoded
        + pack(">IIHB", 0, 0, 0, 0)
        + b"\0" * 67
    )


def _text_tag(text: str) -> bytes:
    return b"text" + b"\0" * 4 + text.encode("ascii") + b"\0"


def _xyz_tag(values: tuple[float, float, float]) -> bytes:
    return b"XYZ " + b"\0" * 4 + _xyz_number(values)


def _xyz_number(values: tuple[float, float, float]) -> bytes:
    return b"".join(_s15_fixed16(value) for value in values)


def _s15_fixed16(value: float) -> bytes:
    return pack(">i", round(value * 65536))


def _transfer_curve(space: RGBColorSpace) -> bytes:
    if space.transfer == "srgb":
        values = _sample_curve(_srgb_to_linear)
    elif space.transfer == "gamma" and space.gamma is not None:
        values = _sample_curve(lambda value: value**space.gamma)
    else:
        raise ValueError(f"unsupported transfer curve '{space.transfer}'")
    body = bytearray(b"curv" + b"\0" * 4 + pack(">I", len(values)))
    for value in values:
        body.extend(pack(">H", value))
    return bytes(body)


def _sample_curve(function: Callable[[float], float]) -> list[int]:
    values: list[int] = []
    for index in range(CURVE_SAMPLES):
        encoded = index / (CURVE_SAMPLES - 1)
        linear = function(encoded)
        values.append(round(min(1.0, max(0.0, linear)) * 65535))
    return values


def _srgb_to_linear(value: float) -> float:
    if value <= 0.04045:
        return value / 12.92
    return ((value + 0.055) / 1.055) ** 2.4


def _xy_to_xyz(xy: tuple[float, float]) -> tuple[float, float, float]:
    x, y = xy
    return (x / y, 1.0, (1.0 - x - y) / y)


def _solve_3x3(
    matrix: tuple[tuple[float, float, float], ...],
    vector: tuple[float, float, float],
) -> tuple[float, float, float]:
    inverse = _inverse_3x3(matrix)
    return _matrix_vector_multiply(inverse, vector)


def _inverse_3x3(
    matrix: tuple[tuple[float, float, float], ...],
) -> tuple[tuple[float, float, float], ...]:
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    determinant = (
        a * (e * i - f * h)
        - b * (d * i - f * g)
        + c * (d * h - e * g)
    )
    return (
        (
            (e * i - f * h) / determinant,
            (c * h - b * i) / determinant,
            (b * f - c * e) / determinant,
        ),
        (
            (f * g - d * i) / determinant,
            (a * i - c * g) / determinant,
            (c * d - a * f) / determinant,
        ),
        (
            (d * h - e * g) / determinant,
            (b * g - a * h) / determinant,
            (a * e - b * d) / determinant,
        ),
    )


def _matrix_multiply(
    left: tuple[tuple[float, float, float], ...],
    right: tuple[tuple[float, float, float], ...],
) -> tuple[tuple[float, float, float], ...]:
    return tuple(
        tuple(
            sum(left[row][inner] * right[inner][column] for inner in range(3))
            for column in range(3)
        )
        for row in range(3)
    )


def _matrix_vector_multiply(
    matrix: tuple[tuple[float, float, float], ...],
    vector: tuple[float, float, float],
) -> tuple[float, float, float]:
    return tuple(
        sum(matrix[row][column] * vector[column] for column in range(3))
        for row in range(3)
    )
